# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - /app/node_modules/

stages: 
    - test
    - build
    - deploy

test:
    stage: test
    script:
        - cd app
        - yarn install
        - yarn run test

build:
    stage: build
    script:
        - cd app
        - yarn install
        - CI=false yarn run build

deploy:
    stage: deploy
    script:
        - apt-get update -qq && apt-get install -y -qq sshpass
        - cd app
        - yarn install
        - CI=false yarn run build
        - export SSHPASS=$SSH_PASSWORD
        - sshpass -e scp -o stricthostkeychecking=no build/ $SSH_USERNAME@159.65.125.31:/usr/share/nginx/
        #- sshpass -e ssh $SSH_USERNAME@159.65.125.31 'rm /usr/share/nginx/html.old; mv /usr/share/nginx/html /usr/share/nginx/html.old && mv /usr/share/nginx/build /usr/share/nginx/html'