version: "3"
services: 
    sp-frontend: 
        container_name: sp-frontend
        build: ./
        ports:
            - "3001:3001"
        volumes:
            - ./:/app
            - '/app/app/node_modules'
        restart: always
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        networks: 
            docker_app_network:
                ipv4_address: 172.23.0.3

networks: 
    docker_app_network:    
        driver: bridge
        ipam: 
            config: 
               - subnet: 172.23.0.0/16