name: SP-Frontend Deploy

on:
  release:
    types: [ created ]

defaults:
  run:
    shell: bash

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 3.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: |
        cd app;
        yarn install;
        CI=false yarn run build;
    - name: Upload project via ssh
      uses: appleboy/scp-action@master
      with:
        host: 159.65.125.31
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: "./app/build/"
        target: "/usr/share/nginx/"
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: 159.65.125.31
      username: ${{ secrets.SSH_USERNAME }}
      password: ${{ secrets.SSH_PASSWORD }}
      port: 22
      script: |
        rm -rf /usr/share/nginx/html.old;
        mv /usr/share/nginx/html /usr/share/nginx/html.old && mv /usr/share/nginx/app/build /usr/share/nginx/html
        
